//= require 'vendor/jquery/jquery-1.11.3'
//= require 'vendor/mustache/mustache'
//= require 'vendor/leaflet/leaflet-src'
//= require 'vendor/omnivore/leaflet-omnivore'
//= require 'vendor/leaflet-pip/leaflet-pip'
